### ISSUE TITLE
on upload, what are the authorized JavaScript source URLs and authorized redirect URIs used?

### ISSUE THREAD

**Issue by EGGObat** [atsiksdong/Youtube_Automated_Channel#1]
I've tried using this same script but it gives an error in the credential URLs...

help me, pls

**Comment by atsiksdong** [comment]
Could you send a screenshot of the error

**Comment by EGGObat** [comment]
![image](https://user-images.githubusercontent.com/94849650/146657665-d93effc4-f438-4f9e-8633-e6b151e1a0d9.png)
what urls can i use?


(sorry, i'm layman)

**Comment by atsiksdong** [comment]
you omitted the foward slash at the end http://localhost:8080/

**Comment by atsiksdong** [comment]
Also you can ignore the callback url

**Comment by EGGObat** [comment]
ok, thanks
